version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: 'mongo:latest'
    ports:
      - '27018:27017'
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
